### ISSUE TITLE
Integration: Call Backend API

### ISSUE THREAD

**Issue by yanchen01** [yanchen01/recipe-mini-project-ui#5]
Call backend API to calculate calories for a recipe.

**Comment by hanlinmai** [comment]
We first import axios and then set a constant to convert joule to calorie.

<img width="239" alt="Comment 1" src="https://user-images.githubusercontent.com/44304241/133525284-7489d81e-73e3-4ef5-997c-cbf4a84e5fdf.png">

Then we connect to the website of FDA and search the calorie of the ingredient. After that, we create a for loop to calculate total calories.

<img width="818" alt="Comment 2" src="https://user-images.githubusercontent.com/44304241/133525406-70198063-f961-431f-8016-6f705dc9143f.png">

Finally, we return the final result after all calculations, which are the total calories of all recipes.

**Comment by ghost** [comment]
> When I try to use 'curl url' to get the calories of the ingredients, I find that the values don't match the values on the packages at all. Why does this happen?

We need to convert units if we want to get the values matching. Since the unit used by FDA is joule and the unit on the package is calorie, we need to divide 4.184 in order to match the value in the unit of calorie.

<img width="239" alt="Comment 1" src="https://user-images.githubusercontent.com/44304241/133527067-fd58353f-f990-4322-8b56-7ee2db85d836.png">

**Comment by ghost** [comment]
When we are adding ingredients into our recipe, how do we get the total calories for the whole recipe?

**Comment by ghost** [comment]
> When we are adding ingredients into our recipe, how do we get the total calories for the whole recipe?

We can set up a 'for' loop to calculate as many ingredients as we can. By setting up a 'for' loop, we don't need to specify the number of the ingredients. In the loop, it will transfer unit from joule to calorie. The loop will calculate the sum and finally return a value, which is the total calories.

<img width="818" alt="Comment 2" src="https://user-images.githubusercontent.com/44304241/133527847-3ceeed17-c5d5-4b14-9a57-6e3531b4d3c8.png">

**Comment by yanchen01** [comment]
Done
